### ISSUE TITLE
Can't Choose a Name

### ISSUE THREAD

**Issue by JTTM** [LUNIServer/UniverseServer#14]
On the Falcon Nebula server all the preset names seem to be taken?

**Comment by Xiphoseer** [comment]
I don't know what Falcon broke, but I have no accees to his server and can't debug it. It's a problem on his server and until he can tell me where exactly it goes wrong I can't fix this here as it only happens for him.

**Comment by JTTM** [comment]
Thanks for letting me know! For now I'm using Jonny's server.

On Tue, Oct 6, 2015, 2:46 AM Xiphoseer <notifications@github.com> wrote:

> I don't know what Falcon broke, but I have no accees to his server and
> can't debug it. It's a problem on his server and until he can tell me where
> exactly it goes wrong I can't fix this here as it only happens for him.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LUNIServer/UniverseServer/issues/14#issuecomment-145846110>
> .
>
-- 

- JTTM

**Comment by LEGOCLUB** [comment]
Public Servers are down
