### ISSUE TITLE
Main.cpp World and Auth initialization Broken

### ISSUE THREAD

**Issue by Alanzote** [LUNIServer/UniverseServer#16]
The Auth and World initialization in Main.cpp is broken. Looks like the problem is on the Switch(state) inside the For loop.

**Comment by Timtech** [comment]
Yep, I'm not getting an auth on the new builds, this might be the problem...

**Comment by Alanzote** [comment]
I've reviwed the Main.cpp code, it definitely something with the "Role" variable... Role is initialized as "ROLE_CONSOLE" that initializes the console... somehow in the Swich(state) inside the For loop, there  a problem...

**Comment by Alanzote** [comment]
Found it:
"for (int argi = 0; argi < argc; argi++)"
This is only being executed once. argc is 1 according to Visual Studio.

**Comment by Timtech** [comment]
Wouldn't argc be argument count... does this mean we have to launch with arguments like --auth or what?

**Comment by Alanzote** [comment]
... dunno ... int main (Ln 106) has the argc var.

**Comment by Alanzote** [comment]
They are just called on the for loop, those vars are not set...

**Comment by Timtech** [comment]
That's why I'm thinking argc is the number of arguments passed to the .exe on the command line, since argi is just the counter from 0 to argc. I think that for loop is just reading the args. Maybe we should pass it some args and see if it enables auth.

**Comment by Alanzote** [comment]
@Timtech , I'll try it out.

**Comment by Timtech** [comment]
@Alanzote Let me know what you find :heavy_check_mark:

**Comment by Alanzote** [comment]
Auth Started, but not world...

**Comment by Timtech** [comment]
What about --auth --world

**Comment by Alanzote** [comment]
@Timtech figured out something!
there are 3 if statements at the end of the code, depending on the last argv you initialize auth or world. That part of the code needs changing.

**Comment by Alanzote** [comment]
uh... thinking on something.

**Comment by Timtech** [comment]
Ok

**Comment by Alanzote** [comment]
I can't execute Auth and World at the same time yet, but I move somethings up and down in code.

**Comment by Timtech** [comment]
This must have been done on purpose. Hopefully @Xiphoseer could help us with this. Maybe you're supposed to have two instances with --auth and --world? And what about the char server? This has changed a bit since I last used it (successfully).

**Comment by Alanzote** [comment]
I don't think there is a char server anymore.

**Comment by Alanzote** [comment]
I think something is blocking, like you can't execute this function if these other is running...

**Comment by Timtech** [comment]
I'm done with this today, nice progress on resolving the issue this far though :) hopefully someone else can shine some light on the issue as well.

**Comment by Alanzote** [comment]
Just a question, why is case 2 for?
"case 2:
			{
				bool f = true;
				if (arg.size() > 1){
					if (arg.substr(0, 2) == "--"){
						f = false;
					}
				}
				if (f){
					setting = arg;
					break;
				}
			}"

I am also done for today, I'll try to resolve this later.

**Comment by Xiphoseer** [comment]
Ok, please stop spamming in here whan you don't understand what it does. It's nothing more than some code to use the param "--auth" to start as auth and "--world" to start as world and start in console mode in all other cases. This is not a support forum for non-devs, this is for real bugs.

**Comment by Xiphoseer** [comment]
Btw, that case 2 is to be able to let a arg be called with a parameter and without. Notice the misisng break at the end of it. It checks if the next is a seperate arg and if it is continues to normal parsing.
