### ISSUE TITLE
int main() - Argv and Argc

### ISSUE THREAD

**Issue by Alanzote** [LUNIServer/UniverseServer#19]
I've noticed that Argv is the Path to LUNI Server.exe. Why would you need the path in the for loop?
![screenshot_1](https://cloud.githubusercontent.com/assets/12262606/10870060/3f28d6a2-80a8-11e5-8616-1a4c8578f019.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/12262606/10870061/3f2a46b8-80a8-11e5-909c-abd88cbe83da.png)

**Comment by Alanzote** [comment]
Now I get it, never mind.

**Comment by Xiphoseer** [comment]
Just for other people wondering when they find this issue: argv[] is an array of all arguments the exe is started with, and the first one is always the path to the file itself.
