### ISSUE TITLE
Missions - XML

### ISSUE THREAD

**Issue by Alanzote** [LUNIServer/UniverseServer#21]
Can someone please tell me about the XML configuration in WorldConnection.cpp?

in missions (mis) I can't determine any other mission state after "done". 
I mean, I want the xml code for loading missions that are not complete.

P.S.: I looked and the game .lua scripts and I found a new way of making the missions.

**Comment by Xiphoseer** [comment]
I haven't tried it yet, but there is &lt;cur&gt; with entries like:
>	&lt;cur&gt;
>	&nbsp;&nbsp;&nbsp;&nbsp;&lt;m id="83"&gt;
>	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;sv v="617000"/&gt;
>	&nbsp;&nbsp;&nbsp;&nbsp;&lt;/m&gt;
>	&nbsp;&nbsp;&nbsp;&nbsp;&lt;m id="296"&gt;
>	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;sv v="598"/&gt;
>	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;sv v="142"/&gt;
>	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;sv v="121"/&gt;
>	&nbsp;&nbsp;&nbsp;&nbsp;&lt;/m&gt;
>	&lt;/cur&gt;

I guess id is the mission id and v the current value. Multiple entries might be for multiple things necessary for the goal like killing three _types_ of enemies.

What do you mean with "making" missions with lua?

**Comment by Alanzote** [comment]
not with LUA, I figured out a way of making the missions in a better way, I based on the original code by LU wich is LUA.

**Comment by Alanzote** [comment]
Thanks, this worked.
